# This is a basic workflow to help you get started with Actions

name: Build Site

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the library'
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello! Started build on version ${{ github.event.inputs.version }}!"
