name: Build Site

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the library'
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "New version published for `meister`: ${{ github.event.inputs.version }}"
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npx meister
